/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : qmuni
 #	author : Andrew Grandstaff
 #	12/29/14
 #
 # --------------------------------------------------------------------------------*/



// --- Basics
void login( PA_PluginParameters params );
