/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : new Project
 #	author : Andrew Grandstaff
 #	12/9/14
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

#include <stdio.h>
#include <string.h>

void PluginMain( PA_long32 selector, PA_PluginParameters params )
{
	switch( selector )
	{
// --- a

		case 1 :
			b( params );
			break;

	}
}

// --------------------------------------- a --------------------------------------


void b( PA_PluginParameters params )
{
	PA_long32 a;
	PA_long32 b;
    PA_long32 returnValue;

	a = PA_GetLongParameter( params, 1 );
	b = PA_GetLongParameter( params, 2 );

	
    
    returnValue = a + b;
    
	PA_ReturnLong( params, returnValue );
}

