/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : new Project
 #	author : Andrew Grandstaff
 #	12/9/14
 #
 # --------------------------------------------------------------------------------*/



// --- a
void b( PA_PluginParameters params );
