/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : qmuni
 #	author : Andrew Grandstaff
 #	1/8/15
 #
 # --------------------------------------------------------------------------------*/



// --- Basics
void login( PA_PluginParameters params );
