/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : qmuni
 #	author : Andrew Grandstaff
 #	1/9/15
 #
 # --------------------------------------------------------------------------------*/


enum{
	eCMD_login = 1
};

void InitPlugin();
void DeinitPlugin();

// --- Basics
void login( PA_PluginParameters params );
