/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : BSecure
 #	author : Andrew Grandstaff
 #	12/10/14
 #
 # --------------------------------------------------------------------------------*/


enum{
	eCMD_addNumbers = 1
};

// --- testing
void addNumbers( PA_PluginParameters params );
