/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : BSecure
 #	author : Andrew Grandstaff
 #	12/10/14
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

#include <stdio.h>
#include <string.h>

void PluginMain( PA_long32 selector, PA_PluginParameters params )
{
	switch( selector )
	{
// --- testing

		case eCMD_addNumbers :
			addNumbers( params );
			break;

	}
}

// ------------------------------------ testing -----------------------------------


void addNumbers( PA_PluginParameters params )
{
	PA_long32 a;
	PA_long32 b;
	PA_long32 returnValue = 0;

	a = PA_GetLongParameter( params, 1 );
	b = PA_GetLongParameter( params, 2 );

	// --- write the code of addNumbers here...
    returnValue = a + b;

	PA_ReturnLong( params, returnValue );
}

