/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : TestProject
 #	author : Andrew Grandstaff
 #	12/12/14
 #
 # --------------------------------------------------------------------------------*/



// --- cantBeliev
void addOrSub( PA_PluginParameters params );
