/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : TestProject
 #	author : Andrew Grandstaff
 #	12/12/14
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"
#include "src/http.h"
#include <stdio.h>
#include <string.h>

void PluginMain( PA_long32 selector, PA_PluginParameters params )
{
	switch( selector )
	{
// --- cantBeliev

		case 1 :
			addOrSub( params );
			break;

	}
}

// ---------------------------------- cantBeliev ----------------------------------


void addOrSub( PA_PluginParameters params )
{
	PA_long32 a;
	PA_long32 b;
	PA_long32 returnValue;

	a = PA_GetLongParameter( params, 1 );
	b = PA_GetLongParameter( params, 2 );

    returnValue = a - b;
    HTTP call;
    returnValue = call.addSomeNumbers(a,b);

	PA_ReturnLong( params, returnValue );
}

