/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : BSecure
 #	author : Andrew Grandstaff
 #	12/9/14
 #
 # --------------------------------------------------------------------------------*/



// --- testing
void addNumbers( PA_PluginParameters params );
