
#include <string>
#include <vector>
#include <iostream>

#include "qmuni.h"
#include "session_handler.h"
#include "conversation_model.h"
#include "net.h"


using namespace std;

SessionHandler::SessionHandler() {
	// TODO: make this go away, remove it from header and prototype
	uri_ = QAPI_BASE_URI;
	//plan on making it so the session handler is able to acceess and manipulate each of the models it is responsible for.  
	//Map<int,Model::Model> model_list_;
	m_session_model = new SessionModel(uri_);
	net_ = new Net();

	m_token = "";
}

SessionHandler::SessionHandler(string uri) {
	uri_ = uri;
	m_session_model = new SessionModel(uri_);
	m_token = "";
	//Map<int,Model> model_list_;
	SessionModel m_session_model(uri_);
}

SessionHandler::~SessionHandler() {
	delete m_session_model;
	m_session_model = NULL;
}

string SessionHandler::getUri() {
	return uri_;
}

int SessionHandler::setUri(string uri) {
	uri_ = uri;
	
	return 0;
}
void SessionHandler::debugJson(string json){
m_session_model->debugJson(json);

}
int SessionHandler::login(string email, string code) {
	//debugNet();
	// TODO: this should be generated by the JSON library
	string input = "{\"email\":\""+email+"\",\"code\":\""+code+"\"}";

	// DEBUG:
	//cout << "data: " << input << endl; 
	//cout << "uri: " << uri_ << endl; 
	map<string, string> noHeaders;
	

	// TODO: this should be in the handler
	int status_code = 0;
	string *output = new string();

	// DEBUG:
	// cerr << "URI IS ME:" << uri_ << endl;

	// TODO: this should be in the base model
	status_code = net_->httpPost(uri_, &noHeaders, input, output);

	// TODO: this should be in the handler
	if (status_code == 200 || status_code == 201) {
		//char *json = (char *)output->c_str();
		
		//fetchJson(*output);
	}

	//cout << net->printf();
	delete output;
	output = NULL;

	// BUG THIS LEAKS MEMORY LIKE A BROKEN FIREHYDRANT LEAKS WATER
	return status_code;
}



/*
void SessionHandler::fetchConversationList(){
	
	m_session_model->fetchConversationList();

}

*/
